### ISSUE TITLE
PyCon CZ

### ISSUE THREAD

**Issue by webknjaz** [github-actions-playground/enroll-me#2]
Hi everyone,

Thanks for attending my workshop!

Leave a comment in this issue to receive your own a repository in this organization **with GitHub Actions enabled** _for testing_.

##### How to write a bot on top of GitHub Actions?
* https://tutorial.octomachinery.dev / https://docs.octomachinery.dev / https://octomachinery.dev
* Check out [the `Dockerfile`](../blob/master/Dockerfile) in this repo.

**Comment by Kani999** [comment]
Hello, please create a repository for me.
